name: Build and Publish Container

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

# Make sure we cancel any outstanding workflows that are outdated.
# This should save time & money.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    permissions:
      contents: read       # checkout
      actions: read        # SLSA provenance generator
      id-token: write      # OIDC for keyless Cosign signing
      packages: write      # push image + provenance to GHCR
    uses: TomHennen/wrangle/.github/workflows/build_and_publish_container.yml@v0.1.0
    with:
      path: PATH/TO/FOLDER/WITH/Dockerfile
      imagename: ghcr.io/${{ github.repository }}/YOUR_IMAGE_NAME
      registry: 'ghcr.io'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
