# Copy this file to your repo at .github/workflows/build_shell.yml
# For shell projects with .sh files and/or bats tests.
name: Shell Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  shell-build:
    permissions:
      contents: read
    # TODO(v0.1.0): Update to @v0.1.0 before release
    uses: tomhennen/wrangle/.github/workflows/build_shell.yml@main
