name: Build Tools

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "**" ]
    paths:
      # only rebuild if something related to our docker images changed
      - tools/**
      - workflows/build-tools.yml
      - source/tools/**
      - publish/actions/container/**
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    strategy:
      fail-fast: false
      matrix:
        tool: [source/tools/osv, source/tools/zizmor]
    uses: tomhennen/wrangle/.github/workflows/build_and_publish_container.yml@main
    with:
      path: ${{ matrix.tool }}
      imagename: ghcr.io/tomhennen/wrangle/${{ matrix.tool }}
      registry: 'ghcr.io'
      publish_provenance_for_private_repo: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
