name: Build Tools

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
    paths:
      # only rebuild if something related to our docker images changed
      - tools/**
      - workflows/build-tools.yml
      - source/tools/**
      - publish/actions/container/**
  pull_request:
    branches: [ "**" ]
    paths:
      # only rebuild if something related to our docker images changed
      - tools/**
      - workflows/build-tools.yml
      - source/tools/**
      - publish/actions/container/**
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [source/tools/osv, source/tools/zizmor]
    steps:
    - name: "build and publish"
      uses: tomhennen/wrangle/publish/actions/container@rearrange_publish
      with:
        path: ${{ matrix.tool }}
        imagename: ghcr.io/${{ github.repository }}/${{ matrix.tool }}
        registry: 'ghcr.io'
        github_token: ${{ secrets.GITHUB_TOKEN }}
