name: Build Tools

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
    paths:
      - tools/** # only rebuild if something under tools changed.
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [build_container, osv, zizmor]
    steps:
    - name: "build and publish"
      uses: tomhennen/wrangle/actions/docker_builder@actions_dev
      with:
        path: tools/${{ matrix.tool }}
        imagename: ghcr.io/${{ github.repository }}/tool_${{ matrix.tool }}
        registry: 'ghcr.io'
