name: Check Change
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions: read-all

jobs:
  # Whenever new source is pushed or a PR is received, scan it for any issues
  check-change:
    permissions:
      security-events: write # So we can upload sarif
    uses: tomhennen/wrangle/.github/workflows/scan-source-callable.yml@main
