on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  # Whenever new source is pushed or a PR is received, scan it for any issues
  scan-source:
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write # So we can upload sarif
    uses: tomhennen/wrangle/.github/workflows/check_source.yml@reusable_actions
