name: Check Source Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  scan-source:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write # So we can upload sarif
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Scan the source repo
      id: scan
      run: |
        ./run.sh -r ghcr.io/tomhennen/wrangle osv zizmor
        cat ./metadata/summary.md >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: Upload SARIFs
      if: ${{ false }} # We're still a private repo so we can't enable code scanning. :(
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./metadata/
        category: wrangle
    - uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: ./metadata/