name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build all the images
      run: ./build.sh build_container osv zizmor
    - name: What do we have
      run: docker image ls
    - name: Archive image tarballs
      uses: actions/upload-artifact@v4
      with:
        name: image-tarballs
        path: dist/*.tar
