name: Check Source Code

on:
  workflow_call:

jobs:
  scan-source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Scan the source repo
      id: scan
      run: ./run.sh -r ghcr.io/tomhennen/wrangle osv zizmor
    - name: Generate summary
      if: always()
      run: cat ./metadata/summary.md >> $GITHUB_STEP_SUMMARY
    - name: Scorecard
      uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46
      with:
        results_file: ./metadata/scorecard/scorecard.sarif
        results_format: sarif
        publish_results: false
    - name: Upload SARIFs
      if: ${{ false }} # We're still a private repo so we can't enable code scanning. :(
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./metadata/
        category: wrangle
    - uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: ./metadata/
